In [1]:
import pandas as pd

filter_string = '10'

df_pair_qa = pd.read_csv('../data/medical-diff-vqa-1.0.1/mimic_pair_questions.csv')
df_pair_qa.shape

(700703, 7)

In [2]:
df_pair_qa.head()

,study_id,subject_id,ref_id,question_type,question,answer,split
0,55088298,18936629,54989200,abnormality,what abnormalities are seen in the soft tissues?,atelectasis,train
1,55088298,18936629,54989200,presence,is there edema?,no,train
2,55088298,18936629,54989200,location,is the atelectasis located on the left side or...,left side,train
3,55088298,18936629,54989200,level,what level is the pneumothorax?,minimal,train
4,55088298,18936629,54989200,difference,what has changed compared to the reference image?,the main image has an additional finding of pn...,train

In [3]:
df_pair_qa.dtypes

study_id          int64
subject_id        int64
ref_id            int64
question_type    object
question         object
answer           object
split            object
dtype: object

In [4]:
df_pair_qa_train = df_pair_qa[df_pair_qa['split'] == 'train']
df_pair_qa_train.shape

(560563, 7)

In [5]:
df_pair_qa_val = df_pair_qa[df_pair_qa['split'] == 'val']
df_pair_qa_val.shape

(70070, 7)

In [6]:
df_pair_qa_test = df_pair_qa[df_pair_qa['split'] == 'test']
df_pair_qa_test.shape

(70070, 7)

In [7]:
df_pair_qa_train.head()

,study_id,subject_id,ref_id,question_type,question,answer,split
0,55088298,18936629,54989200,abnormality,what abnormalities are seen in the soft tissues?,atelectasis,train
1,55088298,18936629,54989200,presence,is there edema?,no,train
2,55088298,18936629,54989200,location,is the atelectasis located on the left side or...,left side,train
3,55088298,18936629,54989200,level,what level is the pneumothorax?,minimal,train
4,55088298,18936629,54989200,difference,what has changed compared to the reference image?,the main image has an additional finding of pn...,train

In [8]:
df_pair_qa_train_small = df_pair_qa_train[df_pair_qa_train['subject_id'].astype(str).str.startswith(filter_string)]
df_pair_qa_train_small.head()

,study_id,subject_id,ref_id,question_type,question,answer,split
490765,54875791,10765488,50651250,abnormality,what abnormalities are seen in this image?,"pleural effusion, edema, heart failure",train
490766,54875791,10765488,50651250,presence,is there evidence of pleural effusion in this ...,yes,train
490767,54875791,10765488,50651250,view,which view is this image taken?,PA view,train
490768,54875791,10765488,50651250,location,where is the pleural effusion?,right area and left area,train
490769,54875791,10765488,50651250,level,what level is the edema?,mild,train

In [9]:
df_pair_qa_train_small.shape

(67955, 7)

In [10]:
df_all = pd.read_csv('../data/medical-diff-vqa-1.0.1/mimic_all.csv')
df_all.shape

(227827, 21)

In [11]:
df_all.head()

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,...,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices,dicom_id,view,split,study_date,study_order
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,postero-anterior,train,21800506,1.0
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,postero-anterior,train,21800626,2.0
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,antero-posterior,train,21800723,3.0
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,antero-posterior,train,21800805,4.0
4,10000764,57375967,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1.0,NaN,NaN,096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4,antero-posterior,train,21321015,1.0

In [12]:
df_all.dtypes

subject_id                      int64
study_id                        int64
Atelectasis                   float64
Cardiomegaly                  float64
Consolidation                 float64
Edema                         float64
Enlarged Cardiomediastinum    float64
Fracture                      float64
Lung Lesion                   float64
Lung Opacity                  float64
No Finding                    float64
Pleural Effusion              float64
Pleural Other                 float64
Pneumonia                     float64
Pneumothorax                  float64
Support Devices               float64
dicom_id                       object
view                           object
split                          object
study_date                      int64
study_order                   float64
dtype: object

In [13]:
df_all_train = df_all[df_all['split'] == 'train']
df_all_train.shape

(222750, 21)

In [14]:
df_all_train_small = df_all_train[df_all_train['subject_id'].astype(str).str.startswith(filter_string)]
df_all_train_small.head(10)

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,...,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices,dicom_id,view,split,study_date,study_order
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,postero-anterior,train,21800506,1.0
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,postero-anterior,train,21800626,2.0
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,antero-posterior,train,21800723,3.0
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,antero-posterior,train,21800805,4.0
4,10000764,57375967,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1.0,NaN,NaN,096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4,antero-posterior,train,21321015,1.0
5,10000898,50771383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2a280266-c8bae121-54d75383-cac046f4-ca37aa16,postero-anterior,train,21880312,2.0
6,10000898,54205396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,b75df1bd-0f22d631-52d73526-2ae7b85a-d843b39d,postero-anterior,train,21880113,1.0
7,10000935,50578979,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,-1.0,...,1.0,NaN,1.0,NaN,NaN,d0b71acc-b5a62046-bbb5f6b8-7b173b85-65cdf738,antero-posterior,train,21871016,6.0
8,10000935,51178377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,-1.0,NaN,NaN,9b314ad7-fbcb0422-6db62dfc-732858d0-a5527d8b,antero-posterior,train,21870823,4.0
9,10000935,55697293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,c50494f1-90e2bff5-e9189550-1a4562fd-6ab5204c,postero-anterior,train,21870226,2.0

In [15]:
df_all_train_small.shape

(21806, 21)

In [ ]:
df_pair_qa_train_small.to_csv(f'../data/medical-diff-vqa-1.0.1/mimic_pair_questions_p{filter_string}_train.csv', index=False)

In [ ]:
df_all_train_small.to_csv(f'../data/medical-diff-vqa-1.0.1/mimic_all_p{filter_string}_train.csv', index=False)

In [26]:
import json

with open("../data/medical-diff-vqa-1.0.1/all_diseases.json") as f:
    data = json.load(f)  # this is a list of dicts

# filter elements where subject_id starts with '10'
filtered_data = [item for item in data if str(item["subject_id"]).startswith("10")]

# save filtered results back to JSON
with open(
    f"../data/medical-diff-vqa-1.0.1/all_diseases_{filter_string}.json", "w"
) as f:
    json.dump(filtered_data, f, indent=4)

print(f"Saved {len(filtered_data)} records to filtered_subjects.json")

Saved 22197 records to filtered_subjects.json

In [20]:
df_pair_qa_train_one_patient = df_pair_qa_train_small[df_pair_qa_train_small['subject_id'] == 10000032]
df_all_train_one_patient = df_all_train_small[df_all_train_small['subject_id'] == 10000032]

In [21]:
df_pair_qa_train_one_patient.head()

,study_id,subject_id,ref_id,question_type,question,answer,split
521428,50414267,10000032,53911762,abnormality,what abnormalities are seen in this image?,lung opacity,train
521429,50414267,10000032,53911762,presence,is there lung opacity?,yes,train
521430,50414267,10000032,53911762,view,is this AP view?,no,train
521431,50414267,10000032,53911762,location,where is the lung opacity?,bilateral area,train
521432,53911762,10000032,50414267,difference,what has changed compared to the reference image?,the main image has an additional finding of fr...,train

In [22]:
df_all_train_one_patient.head()

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,...,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices,dicom_id,view,split,study_date,study_order
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,postero-anterior,train,21800506,1.0
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,postero-anterior,train,21800626,2.0
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,antero-posterior,train,21800723,3.0
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,antero-posterior,train,21800805,4.0

In [23]:
df_pair_qa_train_one_patient.to_csv(f'../data/medical-diff-vqa-1.0.1/mimic_pair_questions_1p.csv', index=False)

In [ ]:
df_all_train_one_patient.to_csv(f'../data/medical-diff-vqa-1.0.1/mimic_all_1p.csv', index=False)

In [27]:
with open("../data/medical-diff-vqa-1.0.1/all_diseases.json") as f:
    data = json.load(f)  # this is a list of dicts

# filter elements where subject_id starts with '10'
filtered_data = [item for item in data if str(item["subject_id"]) == '10000032']

# save filtered results back to JSON
with open(
    f"../data/medical-diff-vqa-1.0.1/all_diseases_1p.json", "w"
) as f:
    json.dump(filtered_data, f, indent=4)

print(f"Saved {len(filtered_data)} records to filtered_subjects.json")

Saved 4 records to filtered_subjects.json